export enum ErrorCategory {
  VALIDATION = 'VALIDATION',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  NOT_FOUND = 'NOT_FOUND',
  SYSTEM = 'SYSTEM',
  EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',
}

export enum ErrorCode {
  // Validation
  INVALID_INPUT = 'VAL-001',
  MISSING_FIELD = 'VAL-002',

  // Auth
  UNAUTHORIZED = 'AUTH-001',
  FORBIDDEN = 'AUTH-002',
  TOKEN_EXPIRED = 'AUTH-003',

  // Resource
  RESOURCE_NOT_FOUND = 'RES-001',
  RESOURCE_EXISTS = 'RES-002',

  // System
  INTERNAL_ERROR = 'SYS-001',
  RATE_LIMIT_EXCEEDED = 'SYS-002',
  SERVICE_UNAVAILABLE = 'SYS-003',
}
